### ISSUE TITLE
Multiple subdomain supported?

### ISSUE THREAD

**Issue by Keltere** [lin010151/ddns-scripts_namesilo#1]
Hi, thanks for the work it's working perfectly.
Just a question: to add multiple subdomain i need to create a new service for each one or there is another way?

**Comment by lin010151** [comment]
Multiple subdomain is not supported, sorry. I will consider adding this to my script.

Also, namesilo supports dns wildcard records via the "*" character, see https://www.namesilo.com/Support/DNS-Manager. U can try that. The script supports it.

**Comment by Keltere** [comment]
Thanks for the response, so in the end i just add *.mysite.com to both namesilo and ddns configuration? 

Also i suggest to add this in the readme file.

**Comment by lin010151** [comment]
If you want all your hostnames (except specific records) point to one ip, then yes, just add it like normal subdomain.

Actually, wildcard records is a function provided by namesilo, and **has same usage as other records**. Because of that, the script can 'naturally' have this function without extra coding.

I will mention it, thanks.

**Comment by Keltere** [comment]
Ok i've tried it but i get this error
```
094526       : The host name is *
 094528       : Successfully retrieved the record id from NameSilo
 105912 ERROR : Failed to update the record
 105912       : Response from NameSilo: <?xml version="1.0"?>
<namesilo><request><operation>dnsUpdateRecord</operation><ip></ip></request><reply><code>108</code><detail>Missing parameters for the specified operation</detail></reply></namesilo>
 105913  info :  - TERMINATE
 105913  WARN : PID '5107' exit WITH ERROR '1' at 2018-08-15 10:59
```

EDIT: i get this error just with *

EDIT: on update record function (from line 146) the rrid is empty. I will try to figure why.

**Comment by Keltere** [comment]
Of found the problem on line 130 there is a problem with the current regex, it gives a empty RRID string with * domain

**Comment by Keltere** [comment]
If i change line 129 from:
`_egrep_o "<record_id>([^<]*)</record_id><type>$RRTYPE</type><host>$domain</host>"`
to:
`_egrep_o "<record_id>([^<]*)</record_id><type>$RRTYPE</type><host>\\$domain</host>"`

it will work, so if i just escape * there is no problem. Maybe just add a check and replace if there is a * subdomain

**Comment by lin010151** [comment]
Sorry, it took a long time. I'm not good at writing shell, haha. Maybe i should modify _egrep_o(), what do you think?

**Comment by Keltere** [comment]
Me neither, never used.
I will try to find a good solution and testing it. When i've done i will make a pull request.

**Comment by lin010151** [comment]
Thank you~~

I think i've found a way, but i don't know whether it causes any side effect.

Add this between line 120 and line 121:
```shell
# Escape * wildcard
if [ "$RRHOST" == "*" ]; then
    domain="\\"${domain}
fi
```

**Comment by Keltere** [comment]
I will test it but i found that the primary domain (mysite.com) is not included on the wildcard.
I can resolve this with a CNAME redirecting to the main domain of type A and change just this.

I found out that using the primary domain it's not working.
 ```
182440 ERROR : Unable to find domain specified
 182440       : Response from NameSilo: <?xml version="1.0"?>
<namesilo><request><operation>listDomains</operation><ip></ip></request><reply><code>300</code><detail>success</detail><domains><domain>mysite.com</domain></domains></reply></namesilo>
 182441  info :  - TERMINATE
 182441  WARN : PID '8675' exit WITH ERROR '1' at 2018-08-15 18:24

```

From line 90, if there isn't any subdomain the domain will be split in two but the function is predisposed for tree

**Comment by lin010151** [comment]
Yeah, about that... The wildcard "\*" in wildcard dns records is just similar with normal usage, not the same. For example, "*.example.com" can only match all the "example.com" **with subdomain** like "sub.example.com". It can not match "example.com" (this also called naked domain, some dns services use the "@" symbol to denote an empty hostname, "@.example.com"), and "...sub-sub.sub.example.com", etc...

You can read this https://en.wikipedia.org/wiki/Wildcard_DNS_record

**Comment by lin010151** [comment]
@Keltere If you have any other question besides multiple subdomain, please open another issue. Thanks.
