### ISSUE TITLE
Add to Openwrt's Repo

### ISSUE THREAD

**Issue by christaikobo** [lin010151/ddns-scripts_namesilo#11]
Dear Dev, I would like to revisit https://github.com/lin010151/ddns-scripts_namesilo/issues/3
Thank you for all the work!

**Comment by lin010151** [comment]
Sorry for waiting too long... 

Because Namesilo is not an DDNS service provider, I've decided not to add this script to Openwrt's Repo.

And also, I haven't use Openwrt for a long time. So it may not work well for now.

Sorry about that.

**Comment by christaikobo** [comment]
It's fine, thanks for the update!

I have migrated to Cloudflare anyway lol, as you rightfully pointed out, namesilo is not a DDNS service provider.
