### ISSUE TITLE
about wget errors with bad networking environment

### ISSUE THREAD

**Issue by KingFannie** [lin010151/ddns-scripts_namesilo#4]
Due to bad networking environment,we will meet some wget errors such as "can't establish ssl connocetion" or “empty esponse”.Usually some retrys can solve this.However,whatever the param retry_count is,the scripts exit immediately when occur these errs.Can you help with the problem?
Thank you for the effort of doing this script.

**Comment by lin010151** [comment]
Maybe I didn't use retry_count in my code... I don't use openwrt for a long time, so I kinda forget how to use ddns-scripts "api". Maybe I should transfer my scripts to someone else and help maintain it. Sorry about that~

**Comment by KingFannie** [comment]
It's all right~
Where can I refer ddns-scripts apis? Maybe I ’ll try to add this feature

**Comment by lin010151** [comment]
Just refer to ddns-scripts' [source code](https://github.com/openwrt/packages/tree/master/net/ddns-scripts). Or from [OpenWrt Documents](https://openwrt.org/docs/guide-user/services/ddns/client).
