### ISSUE TITLE
不能 在 /etc/config/ddns  中 添加配置

### ISSUE THREAD

**Issue by WanKa-zone** [lin010151/ddns-scripts_namesilo#5]
尝试通过Putty 添加配置，但是 返回 Permission denied
![image](https://user-images.githubusercontent.com/45703375/120094579-75ab8f00-c164-11eb-910c-72ff53839c49.png)

是否需要通过其它步骤来获取权限呢？

**Comment by lin010151** [comment]
如果我没记错的话，毕竟有比较长的时间没用OpenWrt了，/etc/config/ddns 只是个配置文件吧（根据config这个文件夹名称也能猜到）？你得配置好后，运行或者重启相应的ddns程序才行。OpenWrt是有个网页版的ddns程序的，比较直观点，建议参照这篇指南来操作 https://openwrt.org/zh/docs/guide-user/services/ddns/client 。如果你的网页控制台没有ddns这个程序的话，你得先安装，这篇指南里也有。
