### ISSUE TITLE
同时更新所有A记录

### ISSUE THREAD

**Issue by Calmact** [lin010151/ddns-scripts_namesilo#6]
如果我没理解错的话，目前的版本是更新根域名的A记录，比如abc.com的A记录对应的IP地址，但一般配置时还会配置*.abc.com和www.abc.com两个A记录对应的IP地址，namesilo老旧的解析系统有没有支持通配符式的IP解析，能否实现一次更新查询所有A记录并指向新的IP？

**Comment by lin010151** [comment]
就一条一条更新吧，*.abc.com是一条，www.abc.com是一条，所以两条就行了。我已经很久没碰OpenWrt了...
